os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.2
before_install:
  - eval "$(curl -sL https://raw.githubusercontent.com/ChameleonBot/Scripts/master/configure_ci)"
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift --version
  - swift build
  - swift test
  
